defaults: &defaults
  # adapter: mysql2
  # username: ubuntu
  # password: Key attached
  # host: ec2-52-24-139-4.us-west-2.compute.amazonaws.com
  adapter: mysql2
  username: root #adapter username
  password: root #adapter password
  host: localhost    #host name

development:
  database: exchange_app   #database name
  <<: *defaults

test:
  database: ExchangeApp_test
  <<: *defaults

production:
  database: ExchangeApp_production
  <<: *defaults
